"""add updated_at to rules and splits

Revision ID: 47345a8fd9b7
Revises: 0ef423e7ca2e
Create Date: 2026-05-29 02:40:49.394611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47345a8fd9b7'
down_revision = '0ef423e7ca2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
