"""add_polish_columns

Revision ID: 7da4cd541398
Revises: 9d6851569b3c
Create Date: 2026-05-28 01:58:29.099626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da4cd541398'
down_revision = '9d6851569b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('plaid_transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('budget_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('budget_id')
        batch_op.drop_column('plaid_transaction_id')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
